server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: syslog
  syslog:
    listen_address: 0.0.0.0:5000
    idle_timeout: 60s
    label_structured_data: yes
    labels:
      job: "syslog"
  pipeline_stages:
    - json:
        expressions:
          service: service
    - labels:
        service:
